/**
 * Per-source configuration. Each object drives BrowseView, DocView,
 * and ChunksView generically — no source-specific component code needed.
 */

export const SOURCES = {
  arxiv: {
    key: 'arxiv',
    label: 'Arxiv',
    subtitle: 'Research papers',
    listEndpoint: '/arxiv/papers',
    detailEndpoint: (id) => `/arxiv/papers/${id}`,
    contentEndpoint: (id) => `/arxiv/papers/${id}/content`,
    chunksEndpoint: '/arxiv/chunks',
    docChunksEndpoint: '/arxiv/doc-chunks',
    embedEndpoint: (id) => `/arxiv/papers/${id}/embed`,
    idField: 'id',
    titleField: 'title',
    subtitle_fn: (item) => (item.authors || []).slice(0, 3).join(', '),
    meta_fn: (item) => item.submitted_date || '',
    contentType: 'html',
    metaFields: [
      { label: 'ID',         value: (d) => d.id },
      { label: 'Authors',    value: (d) => (d.authors || []).join(', ') },
      { label: 'Submitted',  value: (d) => d.submitted_date },
      { label: 'Updated',    value: (d) => d.updated_date },
      { label: 'Category',   value: (d) => d.primary_category },
      { label: 'Categories', value: (d) => (d.categories || []).join(', ') },
      { label: 'DOI',        value: (d) => d.doi },
      { label: 'Journal',    value: (d) => d.journal_ref },
      { label: 'Comments',   value: (d) => d.comments },
    ],
    filters: [
      { key: 'q',              label: 'Search',     type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'category',        label: 'Category', type: 'text',   placeholder: 'e.g. cs or cs.AI' },
      { key: 'author',         label: 'Author',     type: 'text',   placeholder: 'substring' },
      { key: 'submitted_year', label: 'Year',       type: 'number', placeholder: '2023' },
      { key: 'has_html',       label: 'Has HTML',   type: 'boolean' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',              label: 'Default' },
        { value: 'submitted_desc', label: 'Newest first' },
        { value: 'submitted_asc', label: 'Oldest first' },
        { value: 'relevance',     label: 'Relevance' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  openalex: {
    key: 'openalex',
    label: 'OpenAlex',
    subtitle: 'Academic works',
    listEndpoint: '/openalex/works',
    detailEndpoint: (id) => `/openalex/works/${id}`,
    contentEndpoint: null,
    chunksEndpoint: '/openalex/chunks',
    docChunksEndpoint: '/openalex/doc-chunks',
    embedEndpoint: (id) => `/openalex/works/${id}/embed`,
    idField: 'id',
    titleField: 'title',
    subtitle_fn: (item) => (item.authors || []).slice(0, 3).join(', '),
    meta_fn: (item) => [item.year, item.venue].filter(Boolean).join(' · '),
    contentType: 'none',
    metaFields: [
      { label: 'ID',        value: (d) => d.id },
      { label: 'Authors',   value: (d) => (d.authors || []).join(', ') },
      { label: 'Year',      value: (d) => d.year },
      { label: 'Venue',     value: (d) => d.venue },
      { label: 'Citations', value: (d) => d.cited_by_count },
      { label: 'DOI',       value: (d) => d.doi },
      { label: 'URL',       value: (d) => d.openalex_url },
    ],
    filters: [
      { key: 'q',           label: 'Search',       type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'author',      label: 'Author',       type: 'text',   placeholder: 'substring' },
      { key: 'year',        label: 'Year',         type: 'number', placeholder: '2023' },
      { key: 'cited_by_min', label: 'Min citations', type: 'number', placeholder: '100' },
      // domain / field are the top two levels of the OpenAlex topic hierarchy
      // (exact match against the works.domain / works.field columns). Values are
      // OpenAlex's fixed taxonomy: 4 domains, 26 fields.
      { key: 'domain', label: 'Domain', type: 'select', options: [
        { value: '',                  label: 'Any domain' },
        { value: 'Physical Sciences', label: 'Physical Sciences' },
        { value: 'Life Sciences',     label: 'Life Sciences' },
        { value: 'Health Sciences',   label: 'Health Sciences' },
        { value: 'Social Sciences',   label: 'Social Sciences' },
      ]},
      // `dependsOn: 'domain'` makes this a cascading select: when a domain is
      // chosen, BrowseView shows only options whose `group` matches it (the
      // empty "Any field" option, having no group, always shows). Each field
      // belongs to exactly one domain in OpenAlex's taxonomy.
      { key: 'field', label: 'Field', type: 'select', dependsOn: 'domain', options: [
        { value: '',                                           label: 'Any field' },
        { value: 'Agricultural and Biological Sciences',       label: 'Agricultural and Biological Sciences', group: 'Life Sciences' },
        { value: 'Arts and Humanities',                        label: 'Arts and Humanities',                  group: 'Social Sciences' },
        { value: 'Biochemistry, Genetics and Molecular Biology', label: 'Biochemistry, Genetics and Molecular Biology', group: 'Life Sciences' },
        { value: 'Business, Management and Accounting',        label: 'Business, Management and Accounting',   group: 'Social Sciences' },
        { value: 'Chemical Engineering',                       label: 'Chemical Engineering',                 group: 'Physical Sciences' },
        { value: 'Chemistry',                                  label: 'Chemistry',                            group: 'Physical Sciences' },
        { value: 'Computer Science',                           label: 'Computer Science',                     group: 'Physical Sciences' },
        { value: 'Decision Sciences',                          label: 'Decision Sciences',                    group: 'Social Sciences' },
        { value: 'Dentistry',                                  label: 'Dentistry',                            group: 'Health Sciences' },
        { value: 'Earth and Planetary Sciences',               label: 'Earth and Planetary Sciences',         group: 'Physical Sciences' },
        { value: 'Economics, Econometrics and Finance',        label: 'Economics, Econometrics and Finance',  group: 'Social Sciences' },
        { value: 'Energy',                                     label: 'Energy',                               group: 'Physical Sciences' },
        { value: 'Engineering',                                label: 'Engineering',                          group: 'Physical Sciences' },
        { value: 'Environmental Science',                      label: 'Environmental Science',                group: 'Physical Sciences' },
        { value: 'Health Professions',                         label: 'Health Professions',                   group: 'Health Sciences' },
        { value: 'Immunology and Microbiology',                label: 'Immunology and Microbiology',          group: 'Life Sciences' },
        { value: 'Materials Science',                          label: 'Materials Science',                    group: 'Physical Sciences' },
        { value: 'Mathematics',                                label: 'Mathematics',                          group: 'Physical Sciences' },
        { value: 'Medicine',                                   label: 'Medicine',                             group: 'Health Sciences' },
        { value: 'Neuroscience',                               label: 'Neuroscience',                         group: 'Life Sciences' },
        { value: 'Nursing',                                    label: 'Nursing',                              group: 'Health Sciences' },
        { value: 'Pharmacology, Toxicology and Pharmaceutics', label: 'Pharmacology, Toxicology and Pharmaceutics', group: 'Life Sciences' },
        { value: 'Physics and Astronomy',                      label: 'Physics and Astronomy',                group: 'Physical Sciences' },
        { value: 'Psychology',                                 label: 'Psychology',                           group: 'Social Sciences' },
        { value: 'Social Sciences',                            label: 'Social Sciences',                      group: 'Social Sciences' },
        { value: 'Veterinary',                                 label: 'Veterinary',                           group: 'Health Sciences' },
      ]},
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',                   label: 'Default' },
        { value: 'cited_by_count_desc', label: 'Most cited' },
        { value: 'year_desc',          label: 'Newest first' },
        { value: 'year_asc',           label: 'Oldest first' },
        { value: 'relevance',          label: 'Relevance' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  simplewiki: {
    key: 'simplewiki',
    label: 'SimpleWiki',
    subtitle: 'Wikipedia articles',
    listEndpoint: '/simplewiki/articles',
    detailEndpoint: (id) => `/simplewiki/articles/${id}`,
    contentEndpoint: (id) => `/simplewiki/articles/${id}/content`,
    chunksEndpoint: '/simplewiki/chunks',
    docChunksEndpoint: '/simplewiki/doc-chunks',
    embedEndpoint: (id) => `/simplewiki/articles/${id}/embed`,
    // Opening a #REDIRECT stub auto-navigates to its resolved target (the
    // detail endpoint returns `redirect_to`); the target shows a "Redirected
    // from …" note. See DocView's checkRedirect.
    followsRedirects: true,
    idField: 'page_id',
    titleField: 'title',
    subtitle_fn: () => '',
    meta_fn: (item) => item.text_bytes ? `${Math.round(item.text_bytes / 1024)} KB` : '',
    contentType: 'text',
    metaFields: [
      { label: 'Page ID',   value: (d) => d.page_id },
      { label: 'Namespace', value: (d) => d.namespace },
      { label: 'Revision',  value: (d) => d.revision_id },
      { label: 'Timestamp', value: (d) => d.timestamp },
      { label: 'Size',      value: (d) => d.text_bytes ? `${Math.round(d.text_bytes / 1024)} KB` : '' },
    ],
    filters: [
      { key: 'q',     label: 'Search',        type: 'text', placeholder: 'Title FTS5 search…' },
      { key: 'title', label: 'Title contains', type: 'text', placeholder: 'substring' },
      { key: 'category', label: 'Category', type: 'text', placeholder: 'substring, e.g. actor' },
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  enwiki: {
    key: 'enwiki',
    label: 'enwiki',
    subtitle: 'Full English Wikipedia',
    listEndpoint: '/enwiki/articles',
    detailEndpoint: (id) => `/enwiki/articles/${id}`,
    contentEndpoint: (id) => `/enwiki/articles/${id}/content`,
    chunksEndpoint: '/enwiki/chunks',
    docChunksEndpoint: '/enwiki/doc-chunks',
    embedEndpoint: (id) => `/enwiki/articles/${id}/embed`,
    idField: 'page_id',
    titleField: 'title',
    subtitle_fn: () => '',
    meta_fn: (item) => item.text_bytes ? `${Math.round(item.text_bytes / 1024)} KB` : '',
    contentType: 'text',
    metaFields: [
      { label: 'Page ID',   value: (d) => d.page_id },
      { label: 'Namespace', value: (d) => d.namespace },
      { label: 'Revision',  value: (d) => d.revision_id },
      { label: 'Timestamp', value: (d) => d.timestamp },
      { label: 'Size',      value: (d) => d.text_bytes ? `${Math.round(d.text_bytes / 1024)} KB` : '' },
    ],
    filters: [
      { key: 'q',     label: 'Search',        type: 'text', placeholder: 'Title FTS5 (3+ chars)…' },
      { key: 'title', label: 'Title contains', type: 'text', placeholder: 'substring' },
    ],
  },

  gutenberg: {
    key: 'gutenberg',
    label: 'Gutenberg',
    subtitle: 'Classic literature',
    listEndpoint: '/gutenberg/texts',
    detailEndpoint: (id) => `/gutenberg/texts/${id}`,
    contentEndpoint: (id) => `/gutenberg/texts/${id}/content`,
    chunksEndpoint: '/gutenberg/chunks',
    docChunksEndpoint: '/gutenberg/doc-chunks',
    embedEndpoint: (id) => `/gutenberg/texts/${id}/embed`,
    idField: 'id',
    titleField: 'title',
    subtitle_fn: (item) => item.author || '',
    meta_fn: (item) => [item.language, item.release_date].filter(Boolean).join(' · '),
    contentType: 'text',
    metaFields: [
      { label: 'ID',       value: (d) => d.id },
      { label: 'Author',   value: (d) => d.author },
      { label: 'Language', value: (d) => d.language },
      { label: 'Released', value: (d) => d.release_date },
      { label: 'Size',     value: (d) => d.size_bytes ? `${Math.round(d.size_bytes / 1024)} KB` : '' },
    ],
    filters: [
      { key: 'title',    label: 'Title',    type: 'text', placeholder: 'substring' },
      { key: 'author',   label: 'Author',   type: 'text', placeholder: 'substring' },
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  pydocs: {
    key: 'pydocs',
    label: 'Python Docs',
    subtitle: 'Python documentation',
    listEndpoint: '/pydocs/docs',
    detailEndpoint: (id) => `/pydocs/docs/${id}`,
    contentEndpoint: (id) => `/pydocs/docs/${id}/content`,
    chunksEndpoint: '/pydocs/chunks',
    docChunksEndpoint: '/pydocs/doc-chunks',
    idField: 'doc_path',
    titleField: 'title',
    subtitle_fn: (item) => item.section || '',
    meta_fn: (item) => item.section || '',
    contentType: 'text',
    metaFields: [
      { label: 'Path',    value: (d) => d.doc_path },
      { label: 'Section', value: (d) => d.section },
      { label: 'Title',   value: (d) => d.title },
      { label: 'Size',    value: (d) => d.content_chars ? `${d.content_chars} chars` : '' },
    ],
    filters: [
      { key: 'q',       label: 'Search',  type: 'text', placeholder: 'FTS5 query…' },
      { key: 'section', label: 'Section', type: 'text', placeholder: 'e.g. library' },
      { key: 'title',   label: 'Title',   type: 'text', placeholder: 'substring' },
    ],
  },

  openstax: {
    key: 'openstax',
    label: 'OpenStax',
    subtitle: 'Textbook sections',
    listEndpoint: '/openstax/sections',
    detailEndpoint: (id) => `/openstax/sections/${id}`,
    contentEndpoint: (id) => `/openstax/sections/${id}/content`,
    chunksEndpoint: '/openstax/chunks',
    docChunksEndpoint: '/openstax/doc-chunks',
    embedEndpoint: (id) => `/openstax/sections/${id}/embed`,
    idField: 'section_id',
    titleField: 'title',
    subtitle_fn: (item) => item.book_title || '',
    meta_fn: (item) => item.chapter_number
      ? `Ch. ${item.chapter_number}. ${item.chapter_title || ''}`
      : (item.chapter_title || ''),
    // Section bodies are light Markdown with inline \(…\) / display \[…\]
    // LaTeX; the viewer renders the Markdown and typesets the math (KaTeX).
    contentType: 'markdown',
    metaFields: [
      { label: 'Book',       value: (d) => d.book_title },
      { label: 'Subject',    value: (d) => d.subject },
      { label: 'Chapter',    value: (d) => d.chapter_number
          ? `${d.chapter_number}. ${d.chapter_title || ''}`
          : d.chapter_title },
      { label: 'Section',    value: (d) => d.title },
      { label: 'Objectives', value: (d) => d.objectives },
      { label: 'Size',       value: (d) => d.content_chars ? `${d.content_chars} chars` : '' },
    ],
    filters: [
      { key: 'q',       label: 'Search',  type: 'text', placeholder: 'FTS5 query…' },
      { key: 'book_id', label: 'Book', type: 'select',
        optionsEndpoint: '/openstax/books', valueField: 'book_id',
        labelFn: (b) => b.title, defaultLabel: 'All books' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',          label: 'Document order' },
        { value: 'relevance', label: 'Relevance' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  federal_register: {
    key: 'federal_register',
    label: 'Federal Register',
    subtitle: 'U.S. federal rules & notices',
    listEndpoint: '/federal_register/documents',
    detailEndpoint: (id) => `/federal_register/documents/${id}`,
    contentEndpoint: (id) => `/federal_register/documents/${id}/content`,
    chunksEndpoint: '/federal_register/chunks',
    docChunksEndpoint: '/federal_register/doc-chunks',
    embedEndpoint: (id) => `/federal_register/documents/${id}/embed`,
    idField: 'document_number',
    titleField: 'title',
    subtitle_fn: (item) => item.agencies || '',
    meta_fn: (item) => item.publication_date || '',
    contentType: 'text',
    metaFields: [
      { label: 'Number',         value: (d) => d.document_number },
      { label: 'Type',           value: (d) => d.type },
      { label: 'Published',      value: (d) => d.publication_date },
      { label: 'Agencies',       value: (d) => d.agencies },
      { label: 'Action',         value: (d) => d.action },
      { label: 'Effective date', value: (d) => d.effective_date },
      { label: 'HTML',           value: (d) => d.html_url },
      { label: 'PDF',            value: (d) => d.pdf_url },
    ],
    filters: [
      { key: 'q',                label: 'Search',   type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'type',             label: 'Type',     type: 'text',   placeholder: 'e.g. Rule' },
      { key: 'agencies',         label: 'Agency',   type: 'text',   placeholder: 'substring' },
      { key: 'publication_year', label: 'Year',     type: 'number', placeholder: '2024' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',          label: 'Newest first' },
        { value: 'oldest',    label: 'Oldest first' },
        { value: 'relevance', label: 'Relevance' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  github_readmes: {
    key: 'github_readmes',
    label: 'GitHub READMEs',
    subtitle: 'Open-source project READMEs',
    listEndpoint: '/github/readmes',
    detailEndpoint: (id) => `/github/readmes/${id}`,
    contentEndpoint: (id) => `/github/readmes/${id}/content`,
    chunksEndpoint: '/github/chunks',
    docChunksEndpoint: '/github/doc-chunks',
    embedEndpoint: (id) => `/github/readmes/${id}/embed`,
    idField: 'repo',
    titleField: 'repo',
    subtitle_fn: (item) => item.name || '',
    meta_fn: (item) => item.source_list || '',
    contentType: 'text',
    metaFields: [
      { label: 'Repo',        value: (d) => d.repo },
      { label: 'Name',        value: (d) => d.name },
      { label: 'Owner',       value: (d) => d.owner },
      { label: 'Source list', value: (d) => d.source_list },
      { label: 'Size',        value: (d) => d.readme_chars ? `${d.readme_chars.toLocaleString()} chars` : '' },
    ],
    filters: [
      { key: 'q',           label: 'Search',      type: 'text', placeholder: 'FTS5 query…' },
      { key: 'owner',       label: 'Owner',       type: 'text', placeholder: 'substring' },
      { key: 'source_list', label: 'Source list', type: 'text', placeholder: 'exact match' },
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  factbook: {
    key: 'factbook',
    label: 'Factbook',
    subtitle: 'CIA World Factbook',
    listEndpoint: '/factbook/countries',
    detailEndpoint: (id) => `/factbook/countries/${id}`,
    contentEndpoint: null,
    chunksEndpoint: '/factbook/chunks',
    docChunksEndpoint: '/factbook/doc-chunks',
    // The list row is slim (id/name/region); the country profile (`data`) only
    // comes from the detail endpoint, so DocView must fetch it.
    fetchDetail: true,
    idField: 'id',
    titleField: 'name',
    subtitle_fn: (item) => item.region || '',
    meta_fn: (item) => item.region || '',
    contentType: 'none',
    metaFields: [
      { label: 'Code',   value: (d) => d.id },
      { label: 'Name',   value: (d) => d.name },
      { label: 'Region', value: (d) => d.region },
    ],
    filters: [
      { key: 'name', label: 'Country', type: 'text', placeholder: 'substring, e.g. "land"' },
    ],
  },

  worldbank: {
    key: 'worldbank',
    label: 'World Bank',
    subtitle: 'Indicator data',
    listEndpoint: '/worldbank/indicators',
    detailEndpoint: (id) => `/worldbank/indicators/${id}`,
    // No content endpoint; the indicator's "body" is the values table fetched
    // separately via valuesEndpoint and rendered as a table by DocView.
    contentEndpoint: null,
    valuesEndpoint: (id) => `/worldbank/indicators/${id}/values`,
    idField: 'id',
    titleField: 'name',
    subtitle_fn: (item) => item.unit || '',
    meta_fn: (item) => (item.topics || []).slice(0, 2).join(' · '),
    contentType: 'values',
    metaFields: [
      { label: 'ID',          value: (d) => d.id },
      { label: 'Unit',        value: (d) => d.unit },
      { label: 'Source',      value: (d) => d.source_org },
      { label: 'Topics',      value: (d) => (d.topics || []).join(', ') },
      { label: 'Description', value: (d) => d.source_note },
    ],
    filters: [
      { key: 'q',     label: 'Search', type: 'text',   placeholder: 'substring of indicator name' },
      { key: 'topic', label: 'Topic',  type: 'number', placeholder: 'topic id 1–21' },
    ],
  },

  geonames: {
    key: 'geonames',
    label: 'GeoNames',
    subtitle: 'Geographic places',
    listEndpoint: '/geonames/places',
    detailEndpoint: (id) => `/geonames/places/${id}`,
    contentEndpoint: null,
    chunksEndpoint: null,
    idField: 'geonameid',
    titleField: 'name',
    subtitle_fn: (item) => item.feature_description || '',
    meta_fn: (item) => [
      item.country_name,
      item.population ? `pop ${item.population.toLocaleString()}` : '',
    ].filter(Boolean).join(' · '),
    contentType: 'none',
    metaFields: [
      { label: 'GeoName ID',  value: (d) => d.geonameid },
      { label: 'Name',        value: (d) => d.name },
      { label: 'Feature',     value: (d) => d.feature_description },
      { label: 'Feature code', value: (d) => d.feature_class && d.feature_code ? `${d.feature_class}.${d.feature_code}` : '' },
      { label: 'Country',     value: (d) => d.country_name },
      { label: 'Country code', value: (d) => d.country_code },
      { label: 'Latitude',    value: (d) => d.latitude },
      { label: 'Longitude',   value: (d) => d.longitude },
      { label: 'Population',  value: (d) => d.population ? d.population.toLocaleString() : '' },
      { label: 'Elevation',   value: (d) => d.elevation != null ? `${d.elevation} m` : '' },
      { label: 'Timezone',    value: (d) => d.timezone },
      { label: 'Description', value: (d) => d.sentence },
    ],
    filters: [
      { key: 'q',              label: 'Search',       type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'country_code',   label: 'Country code', type: 'text',   placeholder: 'e.g. US' },
      {
        key: 'feature_class',
        label: 'Feature class',
        type: 'multiselect',
        optionsEndpoint: '/geonames/feature_classes',
        valueField: 'feature_class',
        labelFn: (o) => `${o.feature_class} — ${o.name}`,
      },
      {
        key: 'feature_code',
        label: 'Feature code',
        type: 'multiselect',
        optionsEndpoint: '/geonames/feature_codes',
        valueField: 'feature_code',
        labelFn: (o) => `${o.feature_code} — ${o.description || ''}`,
        // Re-fetches when the parent (`feature_class`) selection changes;
        // BrowseView silently drops any selected codes that no longer match.
        dependsOn: 'feature_class',
      },
      { key: 'min_population', label: 'Min population', type: 'number', placeholder: '10000' },
    ],
  },

  sec_edgar: {
    key: 'sec_edgar',
    label: 'SEC EDGAR',
    subtitle: 'U.S. company filings (10-K)',
    listEndpoint: '/sec_edgar/filings',
    detailEndpoint: (id) => `/sec_edgar/filings/${id}`,
    contentEndpoint: (id) => `/sec_edgar/filings/${id}/content`,
    chunksEndpoint: '/sec_edgar/chunks',
    docChunksEndpoint: '/sec_edgar/doc-chunks',
    // On-demand body fetch: filings are harvested as metadata only; the
    // "Download full filing" button pulls the body from SEC. The button shows
    // only when the open filing has no body yet (body_chars falsy).
    downloadEndpoint: (id) => `/sec_edgar/filings/${id}/download`,
    embedEndpoint: (id) => `/sec_edgar/filings/${id}/embed`,
    bodyField: 'body_chars',
    idField: 'accession_number',
    titleField: 'company_name',
    subtitle_fn: (item) => item.form_type || '',
    meta_fn: (item) => item.date_filed || '',
    // Filing bodies are now served as render-ready HTML (body_html); the
    // Content tab v-html's them like arxiv. Older rows fetched before
    // body_html existed fall back to <pre>-wrapped text server-side.
    contentType: 'html',
    metaFields: [
      { label: 'Company',   value: (d) => d.company_name },
      { label: 'CIK',       value: (d) => d.cik },
      { label: 'Form',      value: (d) => d.form_type },
      { label: 'Filed',     value: (d) => d.date_filed },
      { label: 'Accession', value: (d) => d.accession_number },
      { label: 'Size',      value: (d) => d.body_chars ? `${d.body_chars.toLocaleString()} chars` : '' },
      { label: 'URL',       value: (d) => d.filing_url },
    ],
    filters: [
      { key: 'q',       label: 'Search',  type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'company', label: 'Company', type: 'text',   placeholder: 'substring' },
      { key: 'cik',     label: 'CIK',     type: 'text',   placeholder: 'exact match' },
      { key: 'year',    label: 'Year',    type: 'number', placeholder: '2024' },
      { key: 'downloaded', label: 'Body', type: 'select', options: [
        { value: '',      label: 'All filings' },
        { value: 'true',  label: 'Downloaded only' },
        { value: 'false', label: 'Not downloaded' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  eurlex: {
    key: 'eurlex',
    label: 'EUR-Lex',
    subtitle: 'EU legislation',
    listEndpoint: '/eurlex/laws',
    detailEndpoint: (id) => `/eurlex/laws/${id}`,
    contentEndpoint: (id) => `/eurlex/laws/${id}/content`,
    chunksEndpoint: '/eurlex/chunks',
    docChunksEndpoint: '/eurlex/doc-chunks',
    embedEndpoint: (id) => `/eurlex/laws/${id}/embed`,
    idField: 'celex',
    titleField: 'act_name',
    subtitle_fn: (item) => item.act_type || '',
    meta_fn: (item) => [item.date_publication, item.status].filter(Boolean).join(' · '),
    contentType: 'text',
    metaFields: [
      { label: 'CELEX',              value: (d) => d.celex },
      { label: 'Act type',           value: (d) => d.act_type },
      { label: 'Status',             value: (d) => d.status },
      { label: 'Authors',            value: (d) => (d.authors || []).join('; ') },
      { label: 'Date document',      value: (d) => d.date_document },
      { label: 'Date publication',   value: (d) => d.date_publication },
      { label: 'Treaty',             value: (d) => d.treaty },
      { label: 'Legal basis',        value: (d) => d.legal_basis_celex },
      { label: 'First in force',     value: (d) => d.first_entry_into_force },
      { label: 'Cites',              value: (d) => (d.act_cites || []).join('; ') },
      { label: 'Amends',             value: (d) => (d.act_amends || []).join('; ') },
      { label: 'EUROVOC',            value: (d) => (d.eurovoc || []).join('; ') },
      { label: 'Subject matter',     value: (d) => (d.subject_matter || []).join('; ') },
      { label: 'EUR-Lex',            value: (d) => d.eurlex_link },
      { label: 'ELI',                value: (d) => d.eli_link },
      { label: 'Proposal',           value: (d) => d.proposal_link },
      { label: 'OEIL',               value: (d) => d.oeil_link },
      { label: 'Size',               value: (d) => d.text_chars ? `${d.text_chars.toLocaleString()} chars` : '' },
    ],
    filters: [
      { key: 'q',        label: 'Search',   type: 'text',   placeholder: 'FTS5 query… (requires index)' },
      { key: 'act_type', label: 'Act type', type: 'text',   placeholder: 'e.g. Regulation' },
      { key: 'status',   label: 'Status',   type: 'select', options: [
        { value: '',           label: 'Any status' },
        { value: 'In Force',   label: 'In Force' },
        { value: 'Not in Force', label: 'Not in Force' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  billstatus: {
    key: 'billstatus',
    label: 'Bill status',
    subtitle: 'U.S. Congressional bills',
    listEndpoint: '/billstatus/bills',
    detailEndpoint: (id) => `/billstatus/bills/${id}`,
    contentEndpoint: (id) => `/billstatus/bills/${id}/content`,
    chunksEndpoint: null,
    idField: 'bill_id',
    titleField: 'title',
    subtitle_fn: (item) => item.sponsor || '',
    meta_fn: (item) => [
      item.bill_id,
      item.introduced_date,
      item.policy_area,
    ].filter(Boolean).join(' · '),
    contentType: 'text',
    metaFields: [
      { label: 'Bill ID',     value: (d) => d.bill_id },
      { label: 'Congress',    value: (d) => d.congress },
      { label: 'Type',        value: (d) => d.bill_type },
      { label: 'Number',      value: (d) => d.bill_number },
      { label: 'Sponsor',     value: (d) => d.sponsor },
      { label: 'Introduced',  value: (d) => d.introduced_date },
      { label: 'Policy area', value: (d) => d.policy_area },
      { label: 'Subjects',    value: (d) => (d.subjects || []).join('; ') },
      { label: 'Latest action', value: (d) => d.latest_action },
      { label: 'Summary',     value: (d) => d.summary_chars ? `${d.summary_chars.toLocaleString()} chars` : '' },
    ],
    filters: [
      { key: 'q',           label: 'Search',      type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'congress',    label: 'Congress',    type: 'number', placeholder: 'e.g. 118' },
      { key: 'bill_type',   label: 'Type',        type: 'select', options: [
        { value: '',        label: 'Any type' },
        { value: 'HR',      label: 'HR — House bill' },
        { value: 'S',       label: 'S — Senate bill' },
        { value: 'HRES',    label: 'HRES — House simple resolution' },
        { value: 'SRES',    label: 'SRES — Senate simple resolution' },
        { value: 'HCONRES', label: 'HCONRES — House concurrent res.' },
        { value: 'SCONRES', label: 'SCONRES — Senate concurrent res.' },
        { value: 'HJRES',   label: 'HJRES — House joint resolution' },
        { value: 'SJRES',   label: 'SJRES — Senate joint resolution' },
      ]},
      { key: 'sponsor',     label: 'Sponsor',     type: 'text',   placeholder: 'substring' },
      { key: 'policy_area', label: 'Policy area', type: 'text',   placeholder: 'exact match' },
      { key: 'subject',     label: 'Subject',     type: 'text',   placeholder: 'substring' },
    ],
  },

  ecfr: {
    key: 'ecfr',
    label: 'eCFR',
    subtitle: 'U.S. federal regulations',
    listEndpoint: '/ecfr/regulations',
    detailEndpoint: (id) => `/ecfr/regulations/${id}`,
    contentEndpoint: (id) => `/ecfr/regulations/${id}/content`,
    chunksEndpoint: '/ecfr/chunks',
    docChunksEndpoint: '/ecfr/doc-chunks',
    embedEndpoint: (id) => `/ecfr/regulations/${id}/embed`,
    idField: 'id',
    titleField: 'heading',
    subtitle_fn: (item) => item.title_name || '',
    meta_fn: (item) => [
      item.title_num ? `Title ${item.title_num}` : '',
      item.part,
      item.section,
    ].filter(Boolean).join(' · '),
    contentType: 'text',
    metaFields: [
      { label: 'ID',      value: (d) => d.id },
      { label: 'Title',   value: (d) => d.title_num ? `${d.title_num} — ${d.title_name || ''}` : '' },
      { label: 'Chapter', value: (d) => d.chapter },
      { label: 'Part',    value: (d) => d.part },
      { label: 'Section', value: (d) => d.section },
      { label: 'Heading', value: (d) => d.heading },
      { label: 'Size',    value: (d) => d.content_chars ? `${d.content_chars.toLocaleString()} chars` : '' },
    ],
    filters: [
      { key: 'q',     label: 'Search', type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'title', label: 'Title',  type: 'number', placeholder: 'CFR title 1–50' },
      { key: 'part',  label: 'Part',   type: 'text',   placeholder: 'substring' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',          label: 'Document order' },
        { value: 'relevance', label: 'Relevance' },
      ]},
      { key: 'embedded', label: 'Embedding', type: 'radio', options: [
        { value: '',      label: 'All' },
        { value: 'true',  label: 'Embedded only' },
        { value: 'false', label: 'Unembedded only' },
      ]},
    ],
  },

  pdfs: {
    key: 'pdfs',
    label: 'PDFs',
    subtitle: 'Dropped PDF documents',
    listEndpoint: '/pdfs/documents',
    detailEndpoint: (id) => `/pdfs/documents/${encodeURIComponent(id)}`,
    contentEndpoint: (id) => `/pdfs/documents/${encodeURIComponent(id)}/content`,
    // Page-aware semantic search: chunk sections are page labels ("p. 42"), so a
    // hit deep-links the viewer to its page via a #page=N fragment (see DocView).
    chunksEndpoint: '/pdfs/chunks',
    docChunksEndpoint: '/pdfs/doc-chunks',
    // Live per-PDF embed button (whole document, page-aware). A big PDF is many
    // pages, so a click can take minutes of Ollama time — see the route docstring.
    embedEndpoint: (id) => `/pdfs/documents/${encodeURIComponent(id)}/embed`,
    // idField is the filename stem; embedded PDF `title` metadata is often
    // blank, so the stem doubles as the reliable display title and the parsed
    // title (when present) shows as a meta field.
    idField: 'doc_id',
    titleField: 'doc_id',
    subtitle_fn: (item) => item.title || item.author || '',
    meta_fn: (item) => [
      item.num_pages ? `${item.num_pages} pp` : '',
      item.file_size ? `${Math.round(item.file_size / 1024)} KB` : '',
    ].filter(Boolean).join(' · '),
    // Rendered in an in-browser PDF viewer (an <iframe> pointed straight at
    // contentEndpoint — see DocView's 'pdf' branch). No text fetch, no embed.
    contentType: 'pdf',
    metaFields: [
      { label: 'File',     value: (d) => d.doc_id },
      { label: 'Title',    value: (d) => d.title },
      { label: 'Author',   value: (d) => d.author },
      { label: 'Pages',    value: (d) => d.num_pages },
      { label: 'Size',     value: (d) => d.file_size ? `${Math.round(d.file_size / 1024)} KB` : '' },
      { label: 'Created',  value: (d) => d.creation_date },
      { label: 'Producer', value: (d) => d.producer },
      { label: 'Ingested', value: (d) => d.ingested_at },
    ],
    filters: [
      { key: 'q',      label: 'Search', type: 'text', placeholder: 'FTS5 query…' },
      { key: 'title',  label: 'Title',  type: 'text', placeholder: 'substring' },
      { key: 'author', label: 'Author', type: 'text', placeholder: 'substring' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',          label: 'Relevance (or newest)' },
        { value: 'recent',    label: 'Newest first' },
        { value: 'relevance', label: 'Relevance' },
      ]},
    ],
  },
};

export const SOURCE_ORDER = [
  'arxiv', 'openalex', 'simplewiki', 'enwiki', 'gutenberg',
  'pydocs', 'openstax', 'factbook', 'worldbank', 'geonames',
  'federal_register', 'github_readmes', 'sec_edgar', 'billstatus', 'eurlex', 'ecfr',
  'pdfs',
];
