/**
 * Per-source configuration. Each object drives BrowseView, DocView,
 * and ChunksView generically — no source-specific component code needed.
 */

export const SOURCES = {
  arxiv: {
    key: 'arxiv',
    label: 'Arxiv',
    subtitle: 'Research papers',
    listEndpoint: '/arxiv/papers',
    detailEndpoint: (id) => `/arxiv/papers/${id}`,
    contentEndpoint: (id) => `/arxiv/papers/${id}/content`,
    chunksEndpoint: '/arxiv/chunks',
    docChunksEndpoint: '/arxiv/doc-chunks',
    idField: 'id',
    titleField: 'title',
    subtitle_fn: (item) => (item.authors || []).slice(0, 3).join(', '),
    meta_fn: (item) => item.submitted_date || '',
    contentType: 'html',
    metaFields: [
      { label: 'ID',         value: (d) => d.id },
      { label: 'Authors',    value: (d) => (d.authors || []).join(', ') },
      { label: 'Submitted',  value: (d) => d.submitted_date },
      { label: 'Updated',    value: (d) => d.updated_date },
      { label: 'Category',   value: (d) => d.primary_category },
      { label: 'Categories', value: (d) => (d.categories || []).join(', ') },
      { label: 'DOI',        value: (d) => d.doi },
      { label: 'Journal',    value: (d) => d.journal_ref },
      { label: 'Comments',   value: (d) => d.comments },
    ],
    filters: [
      { key: 'q',              label: 'Search',     type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'primary_category', label: 'Category', type: 'text',   placeholder: 'e.g. cs.AI' },
      { key: 'author',         label: 'Author',     type: 'text',   placeholder: 'substring' },
      { key: 'submitted_year', label: 'Year',       type: 'number', placeholder: '2023' },
      { key: 'has_html',       label: 'Has HTML',   type: 'boolean' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',              label: 'Default' },
        { value: 'submitted_desc', label: 'Newest first' },
        { value: 'submitted_asc', label: 'Oldest first' },
        { value: 'relevance',     label: 'Relevance' },
      ]},
    ],
  },

  openalex: {
    key: 'openalex',
    label: 'OpenAlex',
    subtitle: 'Academic works',
    listEndpoint: '/openalex/works',
    detailEndpoint: (id) => `/openalex/works/${id}`,
    contentEndpoint: null,
    chunksEndpoint: '/openalex/chunks',
    docChunksEndpoint: '/openalex/doc-chunks',
    idField: 'id',
    docIdField: 'openalex_url',
    titleField: 'title',
    subtitle_fn: (item) => (item.authors || []).slice(0, 3).join(', '),
    meta_fn: (item) => [item.year, item.venue].filter(Boolean).join(' · '),
    contentType: 'none',
    metaFields: [
      { label: 'ID',        value: (d) => d.id },
      { label: 'Authors',   value: (d) => (d.authors || []).join(', ') },
      { label: 'Year',      value: (d) => d.year },
      { label: 'Venue',     value: (d) => d.venue },
      { label: 'Citations', value: (d) => d.cited_by_count },
      { label: 'DOI',       value: (d) => d.doi },
      { label: 'URL',       value: (d) => d.openalex_url },
    ],
    filters: [
      { key: 'q',           label: 'Search',       type: 'text',   placeholder: 'FTS5 query…' },
      { key: 'author',      label: 'Author',       type: 'text',   placeholder: 'substring' },
      { key: 'year',        label: 'Year',         type: 'number', placeholder: '2023' },
      { key: 'cited_by_min', label: 'Min citations', type: 'number', placeholder: '100' },
      { key: 'venue',       label: 'Venue',        type: 'text',   placeholder: 'exact match' },
      { key: 'sort', label: 'Sort', type: 'select', options: [
        { value: '',                   label: 'Default' },
        { value: 'cited_by_count_desc', label: 'Most cited' },
        { value: 'year_desc',          label: 'Newest first' },
        { value: 'year_asc',           label: 'Oldest first' },
        { value: 'relevance',          label: 'Relevance' },
      ]},
    ],
  },

  simplewiki: {
    key: 'simplewiki',
    label: 'SimpleWiki',
    subtitle: 'Wikipedia articles',
    listEndpoint: '/simplewiki/articles',
    detailEndpoint: (id) => `/simplewiki/articles/${id}`,
    contentEndpoint: (id) => `/simplewiki/articles/${id}/content`,
    chunksEndpoint: '/simplewiki/chunks',
    docChunksEndpoint: '/simplewiki/doc-chunks',
    embedEndpoint: (id) => `/simplewiki/articles/${id}/embed`,
    idField: 'page_id',
    titleField: 'title',
    subtitle_fn: () => '',
    meta_fn: (item) => item.text_bytes ? `${Math.round(item.text_bytes / 1024)} KB` : '',
    contentType: 'text',
    metaFields: [
      { label: 'Page ID',   value: (d) => d.page_id },
      { label: 'Namespace', value: (d) => d.namespace },
      { label: 'Revision',  value: (d) => d.revision_id },
      { label: 'Timestamp', value: (d) => d.timestamp },
      { label: 'Size',      value: (d) => d.text_bytes ? `${Math.round(d.text_bytes / 1024)} KB` : '' },
    ],
    filters: [
      { key: 'q',     label: 'Search',        type: 'text', placeholder: 'Title FTS5 search…' },
      { key: 'title', label: 'Title contains', type: 'text', placeholder: 'substring' },
    ],
  },

  gutenberg: {
    key: 'gutenberg',
    label: 'Gutenberg',
    subtitle: 'Classic literature',
    listEndpoint: '/gutenberg/texts',
    detailEndpoint: (id) => `/gutenberg/texts/${id}`,
    contentEndpoint: (id) => `/gutenberg/texts/${id}/content`,
    chunksEndpoint: '/gutenberg/chunks',
    docChunksEndpoint: '/gutenberg/doc-chunks',
    idField: 'id',
    titleField: 'title',
    subtitle_fn: (item) => item.author || '',
    meta_fn: (item) => [item.language, item.release_date].filter(Boolean).join(' · '),
    contentType: 'text',
    metaFields: [
      { label: 'ID',       value: (d) => d.id },
      { label: 'Author',   value: (d) => d.author },
      { label: 'Language', value: (d) => d.language },
      { label: 'Released', value: (d) => d.release_date },
      { label: 'Size',     value: (d) => d.size_bytes ? `${Math.round(d.size_bytes / 1024)} KB` : '' },
    ],
    filters: [
      { key: 'title',    label: 'Title',    type: 'text', placeholder: 'substring' },
      { key: 'author',   label: 'Author',   type: 'text', placeholder: 'substring' },
      { key: 'language', label: 'Language', type: 'text', placeholder: 'e.g. en' },
    ],
  },

  wikihow: {
    key: 'wikihow',
    label: 'wikiHow',
    subtitle: 'How-to guides',
    listEndpoint: '/wikihow/articles',
    detailEndpoint: (id) => `/wikihow/articles/${id}`,
    contentEndpoint: (id) => `/wikihow/articles/${id}/content`,
    chunksEndpoint: '/wikihow/chunks',
    docChunksEndpoint: '/wikihow/doc-chunks',
    idField: 'id',
    // RAG doc_id is the guide title (the indexer reassembles whole guides),
    // not the per-step row id — so the per-doc chunk inspector keys on title.
    docIdField: 'title',
    titleField: 'title',
    subtitle_fn: (item) => item.section_label || '',
    meta_fn: (item) => item.section_label || '',
    contentType: 'text',
    metaFields: [
      { label: 'ID',       value: (d) => d.id },
      { label: 'Title',    value: (d) => d.title },
      { label: 'Section',  value: (d) => d.section_label },
      { label: 'Headline', value: (d) => d.headline },
      { label: 'Size',     value: (d) => d.text_chars ? `${d.text_chars} chars` : '' },
    ],
    filters: [
      { key: 'q',             label: 'Search',  type: 'text', placeholder: 'FTS5 query…' },
      { key: 'title',         label: 'Title',   type: 'text', placeholder: 'substring' },
      { key: 'section_label', label: 'Section', type: 'text', placeholder: 'exact match' },
    ],
  },

  pydocs: {
    key: 'pydocs',
    label: 'Python Docs',
    subtitle: 'Python documentation',
    listEndpoint: '/pydocs/docs',
    detailEndpoint: (id) => `/pydocs/docs/${id}`,
    contentEndpoint: (id) => `/pydocs/docs/${id}/content`,
    chunksEndpoint: '/pydocs/chunks',
    docChunksEndpoint: '/pydocs/doc-chunks',
    idField: 'doc_path',
    titleField: 'title',
    subtitle_fn: (item) => item.section || '',
    meta_fn: (item) => item.section || '',
    contentType: 'text',
    metaFields: [
      { label: 'Path',    value: (d) => d.doc_path },
      { label: 'Section', value: (d) => d.section },
      { label: 'Title',   value: (d) => d.title },
      { label: 'Size',    value: (d) => d.content_chars ? `${d.content_chars} chars` : '' },
    ],
    filters: [
      { key: 'q',       label: 'Search',  type: 'text', placeholder: 'FTS5 query…' },
      { key: 'section', label: 'Section', type: 'text', placeholder: 'e.g. library' },
      { key: 'title',   label: 'Title',   type: 'text', placeholder: 'substring' },
    ],
  },

  factbook: {
    key: 'factbook',
    label: 'Factbook',
    subtitle: 'CIA World Factbook',
    listEndpoint: '/factbook/countries',
    detailEndpoint: (id) => `/factbook/countries/${id}`,
    contentEndpoint: null,
    chunksEndpoint: '/factbook/chunks',
    docChunksEndpoint: '/factbook/doc-chunks',
    // The list row is slim (id/name/region); the country profile (`data`) only
    // comes from the detail endpoint, so DocView must fetch it.
    fetchDetail: true,
    idField: 'id',
    titleField: 'name',
    subtitle_fn: (item) => item.region || '',
    meta_fn: (item) => item.region || '',
    contentType: 'none',
    metaFields: [
      { label: 'Code',   value: (d) => d.id },
      { label: 'Name',   value: (d) => d.name },
      { label: 'Region', value: (d) => d.region },
    ],
    filters: [
      { key: 'region', label: 'Region', type: 'text', placeholder: 'exact match' },
    ],
  },
};

export const SOURCE_ORDER = [
  'arxiv', 'openalex', 'simplewiki', 'gutenberg',
  'wikihow', 'pydocs', 'factbook',
];
