"""Inline text-level wikitext converters: bold/italic, wikilinks, external links."""

import html
import re

_SKIP_LINK_NAMESPACES = ("file:", "image:", "media:", "category:")

# [url label] or [url] — URL must be http(s); label may contain inline HTML
# left over from earlier passes (e.g. <em>), so don't HTML-escape it.
_EXTERNAL_LINK_RE = re.compile(r"\[(https?://[^\s\]]+)(?:\s+([^\]]*))?\]")
# Bare URLs after whitespace or start-of-line — keeps URLs inside HTML
# attributes (preceded by `="`) or already-rendered <a> tags untouched.
_BARE_URL_RE = re.compile(r"(?:(?<=^)|(?<=\s))(https?://[^\s<>\"'\]\)]+)")
_URL_TRAILING_PUNCT = ".,;:!?"


def normalize_title(title: str) -> str:
    """Capitalise the first letter of a title (MediaWiki convention)."""
    return title[:1].upper() + title[1:]


def convert_bold_italic(text: str) -> str:
    """Convert '''bold''' and ''italic'' to HTML."""
    # Bold+italic must come before bold and italic individually.
    text = re.sub(r"'''''(.+?)'''''", r"<strong><em>\1</em></strong>", text)
    text = re.sub(r"'''(.+?)'''", r"<strong>\1</strong>", text)
    text = re.sub(r"''(.+?)''", r"<em>\1</em>", text)
    return text


def _pipe_trick_label(target: str) -> str:
    """Derive a display label from a page title per MediaWiki's pipe-trick rules.

    Strip namespace prefix (anything before ``:``), then a trailing parenthetical
    (``Foo (bar)`` → ``Foo``), then a trailing comma clause (``Foo, bar`` → ``Foo``).
    Examples:
        ``Wikipedia:Foo`` → ``Foo``
        ``Foo (bar)``     → ``Foo``
        ``Smith, John``   → ``Smith``
    """
    if ":" in target:
        target = target.split(":", 1)[1]
    target = re.sub(r"\s*\([^)]*\)\s*$", "", target)
    if "," in target:
        target = target.split(",", 1)[0]
    return target.strip()


def _render_link(target: str, label: str, escape_label: bool, trail: str = "") -> str:
    """Render a [[wikilink]] as an in-app navigation anchor.

    The link carries no functional ``href`` — instead it tags the target article
    title (and optional ``#section`` anchor) in ``data-`` attributes and a
    ``wikilink`` class. The front-end intercepts clicks on ``a.wikilink``,
    resolves the title to a ``page_id`` within the current source, and navigates
    there. The stored title is normalised to match how titles live in the DB
    (underscores → spaces, first letter capitalised).
    """
    if target.strip().lower().startswith(_SKIP_LINK_NAMESPACES):
        return ""
    raw_title, _, anchor = target.partition("#")
    title = normalize_title(raw_title.strip().replace("_", " "))
    anchor = anchor.strip()

    if escape_label:
        rendered_label = html.escape(label + trail)
    else:
        rendered_label = label + html.escape(trail)

    attrs = ['class="wikilink"']
    if title:
        attrs.append(f'data-wiki-title="{html.escape(title, quote=True)}"')
    if anchor:
        # Heading ids generated by convert_headings use underscores for spaces.
        attrs.append(f'data-wiki-anchor="{html.escape(anchor.replace(" ", "_"), quote=True)}"')
    return f'<a {" ".join(attrs)}>{rendered_label}</a>'


def convert_links(text: str) -> str:
    """Convert [[Page]] and [[Page|Label]] to in-app wikilink anchors.

    Three forms are recognised:
      ``[[Page|]]``       — pipe trick: label derived from page name
      ``[[Page|Label]]``  — piped label (may contain inline HTML)
      ``[[Page]]``        — page name doubles as label

    All forms absorb a trailing ``[a-z]+`` linktrail so ``[[Page]]s`` renders as
    a single link with label ``Pages`` (MediaWiki English convention).
    """
    # Pipe trick: [[Page|]] — derive label from page name.
    text = re.sub(
        r"\[\[([^\]|]+)\|\]\]([a-z]*)",
        lambda m: _render_link(m.group(1), _pipe_trick_label(m.group(1)), escape_label=True, trail=m.group(2)),
        text,
    )
    # [[Page|Label]] — labels may contain inline HTML (e.g. <code>); don't escape.
    text = re.sub(
        r"\[\[([^\]|]+)\|([^\]]+)\]\]([a-z]*)",
        lambda m: _render_link(m.group(1), m.group(2), escape_label=False, trail=m.group(3)),
        text,
    )
    # [[Page]] — page name doubles as visible label; plain text.
    text = re.sub(
        r"\[\[([^\]|]+)\]\]([a-z]*)",
        lambda m: _render_link(m.group(1), m.group(1), escape_label=True, trail=m.group(2)),
        text,
    )
    return text


def convert_external_links(text: str) -> str:
    """Convert MediaWiki external links to <a target=_blank>.

    Three patterns:
      ``[url label]``  → ``<a …>label</a>`` (label preserved as-is — may contain inline HTML)
      ``[url]``        → ``<a …>[N]</a>`` with an article-scoped counter
      bare ``http://…`` → autolinked, but only when preceded by whitespace or
                          start-of-line so URLs inside HTML attributes (``href="…"``)
                          and existing ``<a>`` tags stay intact.
    """
    counter = [0]

    def replace_bracketed(m: re.Match) -> str:
        url = m.group(1)
        label = (m.group(2) or "").strip()
        if not label:
            counter[0] += 1
            label = f"[{counter[0]}]"
        return f'<a href="{html.escape(url, quote=True)}" target="_blank" rel="noopener noreferrer">{label}</a>'

    text = _EXTERNAL_LINK_RE.sub(replace_bracketed, text)

    def replace_bare(m: re.Match) -> str:
        url = m.group(1)
        # Strip URL-terminating punctuation back into surrounding text so
        # "Visit https://x.com." doesn't make the period part of the link.
        suffix = ""
        while url and url[-1] in _URL_TRAILING_PUNCT:
            suffix = url[-1] + suffix
            url = url[:-1]
        if not url:
            return m.group(0)
        return (
            f'<a href="{html.escape(url, quote=True)}" '
            f'target="_blank" rel="noopener noreferrer">{html.escape(url)}</a>{suffix}'
        )

    text = _BARE_URL_RE.sub(replace_bare, text)
    return text
